spring.datasource.url=jdbc:postgresql://altaria.proxy.rlwy.net:22622/railway
spring.datasource.username=postgres
spring.datasource.password=WJhFUnTMPwHJMePRiQRcagcnIVRApQYF

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true