spring.datasource.url=jdbc:postgresql://altaria.proxy.rlwy.net:10911/railway
spring.datasource.username=postgres
spring.datasource.password=IHRljOoRmFRZXnIHMGYNrCvWghHBpYTT

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=MySuperSecretKeyForLegalOffice2026ApplicationJWT

app.cors.allowed-origin=http://localhost:4200
